version: "3.3"
services:
  snipe-it:
    image: snipe/snipe-it
    env_file: .env
    ports:
      - '6969:80'
    expose:
      - '6969'
    volumes:
      - snipe-vol:/var/lib/snipeit
  snipe-mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - snipesql-vol:/var/lib/mysql

volumes:
  snipesql-vol:
    driver: local
  snipe-vol:
    driver: local
  
  