version: '3.8'

services:
  mailserver:
    image: mailserver/docker-mailserver
    container_name: mailserver
    hostname: mail
    # Change this to your domain, it is used for your email accounts (eg: user@example.com):
    domainname: docker.local
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - ./docker-data/nginx-proxy/certs/:/etc/letsencrypt/
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    cap_add:
      - NET_ADMIN # For Fail2Ban to work


# https://docker-mailserver.github.io/docker-mailserver/edge/examples/tutorials/basic-installation/
# You may need to open ports 25, 587 and 465 on the firewall. For example, with the firewall ufw, run:
# ufw allow 25
# ufw allow 587
# ufw allow 465