services:
  kali-local:
    image: kalilinux/kali-rolling
    volumes:
      - kali-home:/home/kali
    tty: true
    networks:
      - pentesting
    command: ["/bin/bash", "-c", "apt update -y && apt install -y vim whois python3-pip"]

# add some DVMs to test on

volumes:
  kali-home:
    driver: local

networks:
  pentesting: {}