version: "3.8"

services:
  localstack:
    container_name: aws-local
    image: localstack/localstack
    ports:
      - "4566:4566"            # LocalStack Gateway - dashboard is deprecated
      - "4510-4515:4510-4515"  # external services port range
      # - "443:443"              # LocalStack HTTPS Gateway (only required for Pro)
      # - "53:53"                # DNS config (only required for Pro)
      # - "53:53/udp"            # DNS config (only required for Pro)
    env_file: aws-basic.env
    volumes:
      - localstack-volume:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack-volume:
    external: true

