services:
  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    volumes:
      - kali-home:/home/
    tty: true
    networks:
      - pentesting1
    command: ["/bin/bash", "-c", "/home/packages.sh"]
    # restart: "no"

  dvwa:
    image: citizenstig/dvwa:latest
    container_name: dvwa
    volumes:
      - dvwa-home:/home
    networks:
      - pentesting1
    # depends_on:
    #   - kali
# add some DVMs to test on

volumes:
  kali-home:
    external: true
  dvwa-home:
    driver: local

networks:
  pentesting1: {}
  pentesting2: {}